# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.buttonBrowse = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonBrowse.setFont(font)
        self.buttonBrowse.setStyleSheet("font: 14pt \"楷体\";")
        self.buttonBrowse.setObjectName("buttonBrowse")
        self.gridLayout.addWidget(self.buttonBrowse, 1, 1, 1, 1)
        self.buttonAnalyze = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.buttonAnalyze.setFont(font)
        self.buttonAnalyze.setObjectName("buttonAnalyze")
        self.gridLayout.addWidget(self.buttonAnalyze, 1, 2, 1, 1)
        self.buttonGenerateWord = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.buttonGenerateWord.setFont(font)
        self.buttonGenerateWord.setObjectName("buttonGenerateWord")
        self.gridLayout.addWidget(self.buttonGenerateWord, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1, QtCore.Qt.AlignTop)
        self.textEditResult = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditResult.setObjectName("textEditResult")
        self.gridLayout.addWidget(self.textEditResult, 2, 1, 1, 3)
        self.lineEditImagePath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditImagePath.setMinimumSize(QtCore.QSize(0, 19))
        self.lineEditImagePath.setObjectName("lineEditImagePath")
        self.gridLayout.addWidget(self.lineEditImagePath, 0, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "上传图片路径："))
        self.buttonBrowse.setText(_translate("MainWindow", "浏览"))
        self.buttonAnalyze.setText(_translate("MainWindow", "上传图片并分析"))
        self.buttonGenerateWord.setText(_translate("MainWindow", "生成听写本"))
        self.label_2.setText(_translate("MainWindow", "识别结果："))
