# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 71, 21))
        self.label_2.setObjectName("label_2")
        self.lineEditImagePath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditImagePath.setGeometry(QtCore.QRect(130, 30, 321, 31))
        self.lineEditImagePath.setObjectName("lineEditImagePath")
        self.buttonBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBrowse.setGeometry(QtCore.QRect(130, 80, 75, 23))
        self.buttonBrowse.setObjectName("buttonBrowse")
        self.buttonAnalyze = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAnalyze.setGeometry(QtCore.QRect(250, 80, 121, 21))
        self.buttonAnalyze.setObjectName("buttonAnalyze")
        self.textEditResult = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditResult.setGeometry(QtCore.QRect(130, 150, 331, 121))
        self.textEditResult.setObjectName("textEditResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "上传图片路径："))
        self.label_2.setText(_translate("MainWindow", "识别结果："))
        self.buttonBrowse.setText(_translate("MainWindow", "浏览"))
        self.buttonAnalyze.setText(_translate("MainWindow", "上传图片并分析"))
